**Welcome to numpy**

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]],np.int8)

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,1]

6

In [7]:
myarr[0,1] = 45

In [8]:
myarr[0,1]

45

#Array creation: Conversion from other Python structures

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array((32,23,23))

array([32, 23, 23])

In [16]:
zeros=np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.shape

(2, 5)

In [19]:
rng=np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
linespace= np.linspace(1,50,10)

In [24]:
linespace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [25]:
emp = np.empty((4,6))

In [26]:
emp

array([[-4.01694515e-129,  1.36996805e-314,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [30]:
ide=np.identity(45)

In [31]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
ide.shape

(45, 45)

In [33]:
arr = np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr.shape

(99,)

In [38]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [39]:
ar = np.array(x)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [41]:
ar.sum(axis=0)

array([12,  8,  9])

In [42]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar.flat

In [45]:
for item in ar.flat:
   print(item)

1
2
3
4
5
6
7
1
0


In [46]:
ar.ndim

2

In [50]:
ar.size

9

In [51]:
ar.nbytes

36

In [49]:
one=np.array([1,3,4,634,2])

In [52]:
one.argmax()

3

In [53]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int32)

In [54]:
ar.argmin()

8

In [59]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int32)

In [56]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int32)

In [57]:
ar2= np.array([[1,2,3],[4,0,6],[8,1,0]])

In [58]:
ar+ar2

array([[ 2,  4,  6],
       [ 8,  5, 12],
       [15,  2,  0]])

In [60]:
ar*ar2

array([[ 1,  4,  9],
       [16,  0, 36],
       [56,  1,  0]])

In [61]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [62]:
ar.sum()

29

In [63]:
ar.min()

0

In [64]:
ar.max()

7

In [65]:
np.where(ar>5)

(array([1, 2], dtype=int32), array([2, 0], dtype=int32))

In [66]:
np.count_nonzero(ar)

8

In [67]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int32))

In [68]:
import sys

In [69]:
py_ar=[0,4,55,2]

In [71]:
np_ar= np.array(py_ar)

In [72]:
sys.getsizeof(1)*len(py_ar)

64

In [73]:
np_ar.itemsize*np_ar.size

16

**Scipy.org for all numpy attributes**